apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v2
  template:
    metadata:
      labels:
        app: my-app
        version: v2
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: my-app
          image: ahmednageh08/node-app:v2
          ports:
            - containerPort: 4000